# Production Environment Configuration (MySQL / Cloud Database)
spring.datasource.url=jdbc:mysql://localhost:3306/rental_semarang?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=rootpassword

spring.h2.console.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
