spring.application.name=rental-semarang
spring.profiles.active=dev

server.port=8080

# HTTP Gzip Compression Optimization
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024

# Spring Boot Actuator Health Check Config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always